# Generated by Django 5.2.4 on 2025-08-18 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_tokens_user_id_f250ab_idx'), models.Index(fields=['access_token'], name='user_tokens_access__6a56cb_idx'), models.Index(fields=['refresh_token'], name='user_tokens_refresh_48dccb_idx')],
            },
        ),
    ]
