# Generated by Django 5.2.4 on 2025-08-07 10:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space_bookings', '0001_initial'),
        ('space_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('new', 'New'), ('renewals', 'Renewals')], default='new', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('pay_easy', 'PayEasy'), ('convenience_store', 'Convenience Store')], default='credit_card', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='space_bookings.spacebooking')),
                ('space_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='space_members.spacemember')),
            ],
        ),
    ]
