# Generated by Django 5.2.4 on 2025-08-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('working_spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingSpaceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('owner', 'Owner')], default='manager', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_spaces', to=settings.AUTH_USER_MODEL)),
                ('working_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='working_spaces.workingspace')),
            ],
            options={
                'unique_together': {('working_space', 'user')},
            },
        ),
    ]
