# Generated by Django 5.2.4 on 2025-08-07 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('working_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('blocked', 'Blocked'), ('activated', 'Activated')], default='waiting', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='working_spaces.workingspace')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
    ]
