# Generated by Django 5.2.4 on 2025-08-07 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('working_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('blocked', 'Blocked'), ('activated', 'Activated')], default='waiting', max_length=20)),
                ('type', models.CharField(choices=[('private_office', 'Private Office'), ('working_desk', 'Working Desk')], default='working_desk', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='working_spaces.workingspace')),
            ],
        ),
    ]
