# Generated by Django 5.2.4 on 2025-09-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='type',
            new_name='space_type',
        ),
    ]
