# Generated by Django 5.2.4 on 2025-09-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_rename_type_to_space_type'),
        ('working_spaces', '0002_remove_workingspace_location_workingspace_latitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['working_space'], name='space_working_space_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['working_space', 'name'], name='space_working_space_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('working_space', 'name'), name='unique_space_name_per_working_space'),
        ),
    ]
