# Generated by Django 5.2.4 on 2025-09-04 07:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_bookings', '0001_initial'),
        ('spaces', '0003_space_space_working_space_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacebooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 8, 52, 51, 243443, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 7, 53, 10, 993533, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['user', 'status'], name='space_booki_user_id_af14e2_idx'),
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['space', 'start_time'], name='space_booki_space_i_30c63b_idx'),
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['status', 'created_at'], name='space_booki_status_e73ccf_idx'),
        ),
    ]
