# Generated by Django 5.2.4 on 2025-08-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingspace',
            name='location',
        ),
        migrations.AddField(
            model_name='workingspace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workingspace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
